import Head from "next/head";
import { Inter } from "next/font/google";
import { signIn, useSession } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	const { data } = useSession();
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div>
				<button onClick={() => signIn("google")}>Sign in</button>
				<p>asd</p>
			</div>
		</>
	);
}
